/** Lucide icon names used in this project (PascalCase). */
export type IconName = "AlertTriangle" | "ArrowDown" | "ArrowLeft" | "ArrowRight" | "ArrowUp" | "BarChart3" | "Bell" | "Calendar" | "Check" | "ChevronDown" | "Clipboard" | "Command" | "Compass" | "Download" | "Eye" | "EyeOff" | "House" | "Info" | "Laptop" | "LayoutGrid" | "Link2" | "Lock" | "Map" | "MessageSquare" | "Monitor" | "MousePointerClick" | "Pencil" | "Pin" | "Plus" | "Search" | "Settings" | "Shield" | "Smartphone" | "Trash2" | "TriangleAlert" | "Type" | "User" | "Vibrate" | "Volume2" | "X" | "ZoomIn";

export const ICON_SLUGS: Record<IconName, string> = {
  "AlertTriangle": "triangle-alert",
  "ArrowDown": "arrow-down",
  "ArrowLeft": "arrow-left",
  "ArrowRight": "arrow-right",
  "ArrowUp": "arrow-up",
  "BarChart3": "chart-column",
  "Bell": "bell",
  "Calendar": "calendar",
  "Check": "check",
  "ChevronDown": "chevron-down",
  "Clipboard": "clipboard",
  "Command": "command",
  "Compass": "compass",
  "Download": "download",
  "Eye": "eye",
  "EyeOff": "eye-off",
  "House": "house",
  "Info": "info",
  "Laptop": "laptop",
  "LayoutGrid": "layout-grid",
  "Link2": "link-2",
  "Lock": "lock",
  "Map": "map",
  "MessageSquare": "message-square",
  "Monitor": "monitor",
  "MousePointerClick": "mouse-pointer-click",
  "Pencil": "pencil",
  "Pin": "pin",
  "Plus": "plus",
  "Search": "search",
  "Settings": "settings",
  "Shield": "shield",
  "Smartphone": "smartphone",
  "Trash2": "trash-2",
  "TriangleAlert": "triangle-alert",
  "Type": "type",
  "User": "user",
  "Vibrate": "vibrate",
  "Volume2": "volume-2",
  "X": "x",
  "ZoomIn": "zoom-in"
};
